apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: deny-all
spec:
  selector:
    matchLabels:
      app: wisecow
  process:
    matchPaths:
    - path: /bin/*
      action: Block
